# Generated by Django 3.0.6 on 2020-06-10 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='articles.Comment'),
        ),
    ]
